@startuml use-cases-training
left to right direction
skinparam actorStyle awesome
actor User

package "SBERT Model Training" {
    usecase TrainingStart as "Start Training"
    usecase CheckStatus as "Check Training Status"
    usecase ConfigureParameters as "Configure Training Parameters"
}

package "Manage Training Data" {
    usecase SelectDatasets as "Select Triplet Datasets"
    usecase SetValidationDataset as "Set Validation Dataset"
}

User --> TrainingStart
User --> CheckStatus
User --> ConfigureParameters
User --> SelectDatasets
User --> SetValidationDataset
@enduml
